### タイトル検索

GET http://127.0.0.1:8000/api/crawler/network/products?name=波よ聞いてくれ
Accept: */*
Cache-Control: no-cache

### タイトルID検索

GET http://127.0.0.1:8000/api/crawler/network/products?network_id=2&network_key=5622
Accept: */*
Cache-Control: no-cache

### タイトル単体

GET http://127.0.0.1:8000/api/crawler/network/products/9669
Accept: */*
Cache-Control: no-cache

### タイトル単体2

GET http://127.0.0.1:8000/api/crawler/network/products/9744
Accept: */*
Cache-Control: no-cache

### エピソード検索

GET http://127.0.0.1:8000/api/crawler/network/episodes?name=波よ聞いてくれ&episode_name=お前を許さない
Accept: */*
Cache-Control: no-cache

### エピソード単体

GET http://127.0.0.1:8000/api/crawler/network/episodes/186859
Accept: */*
Cache-Control: no-cache

###

